server {
    listen 80;
    server_name localhost;
    root /var/www/public;

    index index.php index.html;
    server_tokens off;

    # Headers de Segurança
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Logs do Nginx
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bloqueio estrito de dotfiles (.env, .git, etc) e arquivos de backup (.bkp)
    location ~ /\.(?!well-known).*|.*\.bkp$ {
        deny all;
        return 404;
    }

    # Bloqueio de pastas sensíveis do Laravel
    location ~ ^/(storage|vendor)/ {
        deny all;
        return 404;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
}
